from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.platypus import HRFlowable

from reportlab.lib import colors

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.pagesizes import letter

from datetime import datetime


def generate_report(
    feedback,
    role,
    filename="interview_report.pdf"
):

    doc = SimpleDocTemplate(
        filename,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    current_date = datetime.now().strftime(
        "%B %d, %Y"
    )

    title = Paragraph(
        "AI Mock Interview Report",
        styles["Title"]
    )

    elements.append(title)

    elements.append(
        Spacer(1, 20)
    )

    metadata = [
        f"<b>Role Applied For:</b> {role}",
        f"<b>Generated On:</b> {current_date}"
    ]

    for item in metadata:

        elements.append(
            Paragraph(
                item,
                styles["BodyText"]
            )
        )

    elements.append(
        Spacer(1, 20)
    )
    elements.append(
        HRFlowable(
        width="100%"
    )
)

    elements.append(
    Spacer(1, 20)
)

    overall_score = round(
        (
            feedback["technical_score"]
            + feedback["communication_score"]
            + feedback["problem_solving"]
            + feedback["confidence"]
        ) / 4,
        1
    )

    overall = Paragraph(
        f"<b>Overall Interview Score:</b> {overall_score}/10",
        styles["Heading2"]
    )

    elements.append(overall)

    elements.append(
        Spacer(1, 20)
    )
    summary = Paragraph(
    """
    The candidate demonstrated strong technical
    understanding and problem-solving abilities.
    Communication skills were clear and structured,
    with good overall interview performance across
    key competency areas.
    """,
    styles["BodyText"]
)

    elements.append(summary)

    elements.append(
    Spacer(1, 20)
)

    table_data = [
        ["Competency", "Score"],
        [
            "Technical Knowledge",
            f"{feedback['technical_score']}/10"
        ],
        [
            "Communication",
            f"{feedback['communication_score']}/10"
        ],
        [
            "Problem Solving",
            f"{feedback['problem_solving']}/10"
        ],
        [
            "Confidence",
            f"{feedback['confidence']}/10"
        ]
    ]

    table = Table(
    table_data,
    colWidths=[250, 100]
)
    table.hAlign = "CENTER"
    table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D6EAF8")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
            colors.whitesmoke,
            colors.lightgrey
        ]),
    ])
)

    elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            "Strengths",
            styles["Heading2"]
        )
    )

    for strength in feedback["strengths"]:

        elements.append(
            Paragraph(
                f"• {strength}",
                styles["BodyText"]
            )
        )

    elements.append(
        Spacer(1, 16)
    )

    elements.append(
        Paragraph(
            "Weaknesses",
            styles["Heading2"]
        )
    )

    for weakness in feedback["weaknesses"]:

        elements.append(
            Paragraph(
                f"• {weakness}",
                styles["BodyText"]
            )
        )

    elements.append(
        Spacer(1, 16)
    )

    elements.append(
        Paragraph(
            "Improvement Suggestions",
            styles["Heading2"]
        )
    )

    for improvement in feedback[
        "improvements"
    ]:

        elements.append(
            Paragraph(
                f"• {improvement}",
                styles["BodyText"]
            )
        )
    elements.append(
    Spacer(1, 30)
)

    footer = Paragraph(
    "Generated by Mock Interview AI",
    styles["Italic"]
)

    elements.append(footer)
    doc.build(elements)

    return filename